### ISSUE TITLE
Incorrect validation in initial ask

### ISSUE THREAD

**Issue by siriak** [wakatara/harsh#10]
I've installed harsh from snap and when I run `ask` for the first time it asks for "How many days back shall we start tracking from in days?" and states that "Starting today would be 0. Choose. (0-7) ". Choosing 0 works, but choosing 7 doesn't:
```
siriak@siriak-laptop:~$ harsh a
Your log file looks empty. Let's setup your tracking.
How many days back shall we start tracking from in days?
harsh will ask you about each habit for every day back.
Starting today would be 0. Choose. (0-7) 
7
Sorry! Please choose a valid number (0-7) 0
2021-07-17:
                  Gymmed                                                             !! [y/n/s/⏎]
```

**To Reproduce**

1. Install a fresh copy of `harsh` from snap
2. Run `harsh l` to create config files
3. Run `harsh a` and enter 7 when asked for days.

**Expected behavior**

I expected 7 to work as stated in command description. I'd also write it as a closed [0; 7] or half-open [0; 7) interval depending on whether 7 is included or not.

**Environment**

- OS: Ubuntu 21.04
- OS version: Linux siriak-laptop 5.11.0-22-generic #23-Ubuntu SMP Thu Jun 17 00:34:23 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
- Harsh version: 0.8.9

**Comment by wakatara** [comment]
Hey @siriak 

#facepalm
Doh. This is just plain embarrassing as a bug. I have a < 7 in the checker instead of <= 7. 

Will be fixed in the next release.

Thanks for reporting it. I really appreciate it. 

Daryl.

**Comment by wakatara** [comment]
This is now fixed in 
https://github.com/wakatara/harsh/releases/tag/v0.8.10
which is available via automatic release by snaps or homebrew. 
Again, thanks for letting me know about the bug.

(also, 0.8.10 adds a new harsh log stats subcommand for >100 days analysis.)
