### ISSUE TITLE
Unexpected output of ask command

### ISSUE THREAD

**Issue by siriak** [wakatara/harsh#13]
`harsh a` prints out some dates for no apparent reason.
```
siriak@siriak-laptop:~$ harsh a
2021-07-11:
2021-07-12:
2021-07-13:
2021-07-14:
2021-07-15:
2021-07-19:
         Habit1                                                           ━━━! [y/n/s/⏎] 
```

**To Reproduce**

1. Install attached configs
2. Run `harsh a`

**Expected behavior**

`harsh` output starts with
```
2021-07-19:
         Habit1                                                           ━━━! [y/n/s/⏎] 
```

**Environment**

- OS: linux
- OS version: Linux siriak-laptop 5.11.0-22-generic #23-Ubuntu SMP Thu Jun 17 00:34:23 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
- Harsh version: 0.8.10

**Note**
I had to add extension .txt to files for GitHub to accept them, please rename them to habits and log without the .txt extension to reproduce the bug.

**Attachments**
[habits.txt](https://github.com/wakatara/harsh/files/6840639/habits.txt)
[log.txt](https://github.com/wakatara/harsh/files/6840618/log.txt)

**Comment by wakatara** [comment]
Heya @siriak 

Sorry to take so long to get round to this. It was in deed a bug, and I just fixed the problem (for both ask and log functions) in the last two commits I just pushed. I'll be making a release for the bug fixes in the next day or so... 

thanks for reporting the bug (I fixed it when I rolled over to a new log file this year just now.), and sorry it took so long for me to get to it. Hopefully you're still using harsh. 

And happy year of the tiger!! 🐯

ciao !
Daryl.
