### ISSUE TITLE
Nixpkg

### ISSUE THREAD

**Issue by LAURAilway** [wakatara/harsh#23]
Are you cool with me packaging harsh for nixos?

**Comment by LAURAilway** [comment]
Added to nixpkgs, will submit PR for updated readme

**Comment by wakatara** [comment]
Hey @LAURAilway 

Sorry, for the late reply. Was on vacation and just got back to HK... 

Happy to have it added to nixpkgs (in fact, if there is a way to goreleaser it, could even make it part of the general release cycle, tho have to admit am not a nix user.)

thanks!
