### ISSUE TITLE
Adjust the size of bars to the current terminal window

### ISSUE THREAD

**Issue by aisneto** [wakatara/harsh#27]
This issue has come to my attention in the latest update. The size of the bars for both "ask" and "log" are not properly formatted in small windows (see the figures). This disrupts the intuitiveness of a graph-based progress report, as it is challenging to understand the bars that are spread across multiple lines, especially now that weekdays are also displayed on the "log".

While this issue is resolved by maximizing the window size, on smaller screens, such as my laptop, the bars are only properly formatted in full-screen mode. This slightly increases the attrition for tracking and logging habits.

A easy implementation (I think!) would be a option in the configuration file to specify the number of columns for which the graph bars should be printed.

![image](https://github.com/wakatara/harsh/assets/105523584/d505c63f-0afc-41a9-8cc9-93f63fe9cd78)
![image](https://github.com/wakatara/harsh/assets/105523584/b84a1f09-5311-41b0-b9bf-17dc4a48d474)

**Comment by wakatara** [comment]
@aisneto 
Hey there!

Well, I'm been moving countries and taking on new supervillain tasks, but just happened to be up late tonight and wanted to do a bit of hacking, soooooo this should be working now. Please help me kick the tires on it. Works fine on all osx terminals and in nvim terminal sizings, but have not... for example, tried it out with a tiling window manager on linux (which is the reason I assume you may be asking. So, please give it a whirl under version 0.10.3.

https://github.com/wakatara/harsh/releases/tag/v0.10.3

thanks!
