### ISSUE TITLE
Log padding sometimes isn't even for each habit (past a certain habit line length?)

### ISSUE THREAD

**Issue by rgrams** [wakatara/harsh#8]
**Describe the bug**

I just started trying out harsh. With certain habit names, the padding on those lines in the log is off--the ends of the graph don't line up vertically. I thought I might have hit an edge case by manually padding out my habit names with spaces so they'd line up on the other side, but I tried replacing all the spaces with a letter and it had the same issue.

Is there some limit to the length of habit names?

This is what I get from `harsh log`: _(the right end of some of the lines is offset)_
```                                                                                                                         ▁▃▃▆ 
             Use harsh.                                                                                                     ━ 
             Bike ride.                                                                                                     ━ 
          Clean studio.                                                                                                     • 
Mowing                                                                                                                      ━─── 
 - paths out back                                                                                                              ━ 
 - around fruit trees                                                                                                          ━ 
 - back lawn                                                                                                                    !
 - side field & drive                                                                                                           !
 - lake path                                                                                                                    !
                   ***.                                                                                                   ━━━!
       Go to bed by 10.                                                                                                   ━━━!
Yesterday's Score: 66.7%

```
If I remove three trailing spaces from each offending habit (in both the habits and the log file so they still match), I get what looks like a correct result:
```
                                                                                                                         ▁▃▃▆ 
             Use harsh.                                                                                                     ━ 
             Bike ride.                                                                                                     ━ 
          Clean studio.                                                                                                     • 
Mowing                                                                                                                   ━─── 
 - paths out back                                                                                                           ━ 
 - around fruit trees                                                                                                       ━ 
 - back lawn                                                                                                                 !
 - side field & drive                                                                                                        !
 - lake path                                                                                                                 !
                   ***.                                                                                                   ━━━!
       Go to bed by 10.                                                                                                   ━━━!
Yesterday's Score: 66.7%
```

**To Reproduce**

habits and log files showing the issue: _(given .txt extension just so I can upload to github)_
[habits.txt](https://github.com/wakatara/harsh/files/6564641/habits.txt)
[log.txt](https://github.com/wakatara/harsh/files/6564642/log.txt)

habits and log files with three spaces removed--they seem to work correctly:
[habits.txt](https://github.com/wakatara/harsh/files/6564646/habits.txt)
[log.txt](https://github.com/wakatara/harsh/files/6564647/log.txt)

**Expected behavior**

I expect each day on the graph to line up vertically, whatever the habit is named.
If there's a limit to how long of habit names the log can show, I would just cut them off rather than messing up the graph.

**Environment**

- OS: Linux Mint 20.1 Ulyssa
- OS version: Linux rossmint 5.4.0-73-generic #82-Ubuntu SMP Wed Apr 14 17:39:42 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
- Harsh version: Harsh version 0.8.8

Thanks!

**Comment by wakatara** [comment]
Hey @rgrams !

Interesting (and thanks for the feedback). Lemme take a boo at it this evening after RPP. May I also ask which terminal-emulator and font you may be using?  (I suspect this is more about the leading spaces you have in the log file where you've gone for the hierarchical effect - I have to admit I had never thought of someone doing that... =] So, may be throwing things off since I don't believe I strip that.).

lemme check it out next day or so, since some work on it is on my todo list.

**Comment by rgrams** [comment]
Cool, thanks! No rush.

I'm using `xfce4-terminal` version 0.8.9.1, with the `Monospace Regular` font at 10pt size.

Yeah, I wasn't actually _trying_ to break things, haha, but I knew it was somewhat unintended usage. I did try removing the leading spaces and any other weird stuff, but it didn't seem to matter. As far as I can tell there's just a limit on the number of characters that the log can handle, and long habit names just push the graph over.

```
                                                                                                                         ▂▂█  
             Use harsh.                                                                                                    ━  
             Bike ride.                                                                                                    ━  
          Clean studio.                                                                                                    •  
Lorem ipsum dolor sit amet, consectetur adipiscing elit                                                                                                    ━!!
Lorem ipsum dolor sit amet, consectetur adipiscing                                                                                                    ━!!
Lorem ipsum dolor sit amet, consectetur adipi                                                                                                    ━!!
Lorem ipsum dolor sit amet, consectetur                                                                                                     ━!!
Lorem ipsum dolor sit amet, consect                                                                                                    ━!!
Lorem ipsum dolor sit amet, co                                                                                                    ━!!
Lorem ipsum dolor sit ame                                                                                                    ━!!
   Lorem ipsum dolor si                                                                                                    ━!!
        Lorem ipsum dol                                                                                                    ━!!
             test habit                                                                                                  ━━━!!
       Go to bed by 10.                                                                                                  ━━━!!
Yesterday's Score: 0.0%
```

---

I'm not familiar with Go, so I might be completely off-base here, but scanning through the code, it looks like line 115...

```fmt.Printf("%25v", habit.Name+"  ")```

...pads the habit name plus two spaces out to 25 characters, so any habit name longer than 23 characters will just push the graph over.

**Comment by wakatara** [comment]
Yes, you are correct on the padding. I am just checking your habits file to confirm that is the problem (and maybe bumping it a bit (sad fix) or dynamically calculating that value for the max + 1 of the length of the max line in the habits file (cool fix).

**Comment by wakatara** [comment]
So, actually the issue is the hierarchical structure you tried to create by padding out the space before the  ":" in the habits file since I had had habits as simple "top level" constructs without realizing people might want sub-habits and structuring it the way you did. 
ie. 

> Mowing                                  : 365¬
> - paths out back                   : 10¬
> - around fruit trees               : 10¬
> - back lawn                           : 10¬

as it tried to right align things to the consistency graph to provide visual coherence with the habit lines (and I thought it looked better... ).

I could increase the 25 pad as you say though it does not really solve the problem as it most likely needs to be dynamic. Note: your terminal also needs to be character wide enough to accommodate the length of the habit line, the pad and the 100 days of habits that gets recorded in the consistency graph when it has enough records.

Lemme take a look at it later. Just on dinner break right now with work.

**Comment by wakatara** [comment]
Hey @rgrams 

I had a little time after work tonight, so updated harsh to do dynamic padding for you. It'll now pad to the left of your longest habit by 10 spaces. I did test it with your specific habit file so should get the effect you, at least for the spaced out hierarchical file.

It's a better solution anyone than the fixed padding so thanks for raising the issue. It's already up as a new release nad available via snaps, go get -u github/waaktara/harsh, or as a snap. 

You can see the generated releases at https://github.com/wakatara/harsh/releases/tag/v0.8.9

bon appetit!

**Comment by rgrams** [comment]
Awesome, works great! Thanks!
